// analyzer.go
package main

import (
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/analysis/singlechecker"
)

var includeGenerated bool

var Analyzer = &analysis.Analyzer{
	Name:     "positionless",
	Doc:      "reports positional struct literal initialization",
	Requires: []*analysis.Analyzer{inspect.Analyzer},
	Run:      run,
}

func init() {
	Analyzer.Flags.BoolVar(&includeGenerated, "generated", false,
		"include generated files in analysis")
}

func run(pass *analysis.Pass) (any, error) {
	// Skip generated files unless explicitly requested
	if !includeGenerated {
		for _, file := range pass.Files {
			if isGeneratedFile(file) {
				continue
			}
			analyzeFile(pass, file)
		}
	} else {
		// Analyze all files including generated ones
		for _, file := range pass.Files {
			analyzeFile(pass, file)
		}
	}

	return nil, nil
}

func isGeneratedFile(file *ast.File) bool {
	for _, comment := range file.Comments {
		for _, c := range comment.List {
			text := strings.ToLower(c.Text)
			if strings.Contains(text, "code generated") ||
				strings.Contains(text, "do not edit") ||
				strings.Contains(text, "autogenerated") {
				return true
			}
		}
	}
	return false
}

func analyzeFile(pass *analysis.Pass, file *ast.File) {
	// Debug: show what files we're processing
	pos := pass.Fset.Position(file.Pos())
	fmt.Printf("Analyzing: %s\n", pos.Filename)

	ast.Inspect(file, func(n ast.Node) bool {
		if cl, ok := n.(*ast.CompositeLit); ok {
			checkCompositeLit(pass, cl)
		}
		return true
	})
}

func checkCompositeLit(pass *analysis.Pass, cl *ast.CompositeLit) {
	if !isPositionalStruct(cl) {
		return
	}

	structType := getStructType(pass, cl)
	if structType == nil {
		return // Not a struct or can't determine type
	}

	if len(cl.Elts) > structType.NumFields() {
		// More elements than fields - unsafe to fix
		return
	}

	fix := createNamedFieldsFix(pass, cl, structType)
	if fix == nil {
		return
	}

	pass.Report(analysis.Diagnostic{
		Pos:            cl.Pos(),
		End:            cl.End(),
		Message:        "positional struct literal initialization is fragile",
		SuggestedFixes: []analysis.SuggestedFix{*fix},
	})
}

func isPositionalStruct(cl *ast.CompositeLit) bool {
	if len(cl.Elts) == 0 {
		return false
	}

	// Check if any element is a key-value pair
	for _, elt := range cl.Elts {
		if _, ok := elt.(*ast.KeyValueExpr); ok {
			return false // Already has named fields
		}
	}

	return true
}

func getStructType(pass *analysis.Pass, cl *ast.CompositeLit) *types.Struct {
	tv, ok := pass.TypesInfo.Types[cl]
	if !ok {
		return nil
	}

	typ := tv.Type
	// Handle pointer to struct
	if ptr, ok := typ.(*types.Pointer); ok {
		typ = ptr.Elem()
	}

	structType, ok := typ.(*types.Struct)
	if !ok {
		return nil
	}

	return structType
}

func createNamedFieldsFix(pass *analysis.Pass, cl *ast.CompositeLit,
	structType *types.Struct) *analysis.SuggestedFix {

	var newText strings.Builder

	// Get the type name for the fix
	_ = pass.Fset.Position(cl.Lbrace)
	newText.WriteString("{\n")

	for i, elt := range cl.Elts {
		if i >= structType.NumFields() {
			return nil // Safety check
		}

		field := structType.Field(i)
		if !field.Exported() {
			return nil // Can't reference unexported fields
		}

		// Get the original text of the element
		eltStart := pass.Fset.Position(elt.Pos())
		eltEnd := pass.Fset.Position(elt.End())

		if eltStart.Filename != eltEnd.Filename {
			return nil // Spans multiple files somehow
		}

		// Read the source text
		src, err := os.ReadFile(eltStart.Filename)
		if err != nil {
			return nil
		}

		eltText := string(src[eltStart.Offset:eltEnd.Offset])

		newText.WriteString(fmt.Sprintf("\t%s: %s,\n", field.Name(), eltText))
	}

	newText.WriteString("}")

	return &analysis.SuggestedFix{
		Message: "convert to named field initialization",
		TextEdits: []analysis.TextEdit{
			{
				Pos:     cl.Lbrace,
				End:     cl.Rbrace + 1,
				NewText: []byte(newText.String()),
			},
		},
	}
}

func main() {
	singlechecker.Main(Analyzer)
}
