name: Test and Tag

on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write
  pull-requests: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Run build
        run: go build -v ./...
